//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFServiceConsumer.JobServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="JobServiceReference.IJobService")]
    public interface IJobService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/OpeningJobs", ReplyAction="http://tempuri.org/IJobService/OpeningJobsResponse")]
        string[] OpeningJobs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/OpeningJobs", ReplyAction="http://tempuri.org/IJobService/OpeningJobsResponse")]
        System.Threading.Tasks.Task<string[]> OpeningJobsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/OpeningJobsByRole", ReplyAction="http://tempuri.org/IJobService/OpeningJobsByRoleResponse")]
        string[] OpeningJobsByRole(string role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/OpeningJobsByRole", ReplyAction="http://tempuri.org/IJobService/OpeningJobsByRoleResponse")]
        System.Threading.Tasks.Task<string[]> OpeningJobsByRoleAsync(string role);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IJobServiceChannel : WCFServiceConsumer.JobServiceReference.IJobService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JobServiceClient : System.ServiceModel.ClientBase<WCFServiceConsumer.JobServiceReference.IJobService>, WCFServiceConsumer.JobServiceReference.IJobService {
        
        public JobServiceClient() {
        }
        
        public JobServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JobServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JobServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JobServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] OpeningJobs() {
            return base.Channel.OpeningJobs();
        }
        
        public System.Threading.Tasks.Task<string[]> OpeningJobsAsync() {
            return base.Channel.OpeningJobsAsync();
        }
        
        public string[] OpeningJobsByRole(string role) {
            return base.Channel.OpeningJobsByRole(role);
        }
        
        public System.Threading.Tasks.Task<string[]> OpeningJobsByRoleAsync(string role) {
            return base.Channel.OpeningJobsByRoleAsync(role);
        }
    }
}
